<?php

/**
 * @file
 * Contains islandora_herbarium.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function islandora_herbarium_object_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the islandora_pdf module.
    case 'help.page.islandora_herbarium':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Islandora Herbarium') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_presave().
 */
function islandora_herbarium_object_entity_presave(Drupal\Core\Entity\EntityInterface $entity)
{
  if ($entity->bundle() == 'islandora_herbarium_object') {
    // Get the geo data.
    $geo = \Drupal::service('islandora_herbarium_object.geoparser');
    $geo->updateEntity($entity);
    // Get the taxonomy data.
    $taxon = \Drupal::service('islandora_herbarium_object.taxonparser');
    $taxon->updateEntity($entity);

    $title =  $taxon->getValue('canonicalName') . ' - ' .  $geo->getValue('name');
    if(!empty($title)) {
      $entity->setTitle($title);
    }

  }
}



